name: Pipeline

permissions:
  contents: "write"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    if: false
    uses: horowitzathome/rust-workflows/.github/workflows/check.yaml@main
  test:
    uses: horowitzathome/rust-workflows/.github/workflows/test.yaml@main
  build:
    uses: horowitzathome/rust-workflows/.github/workflows/build_all.yaml@main
    needs: test
    with:
      image: horowitzathome/mandel-rust
    secrets:
      container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
